AUDIO_SAMPLERATE: 16000
BATCH_SIZE: 128
DIR_NAME_MODEL: model
DIR_NAME_RESULT: result
DIR_NAME_TEST_LOGMEL: tr/test_logmel
DIR_NAME_TEST_STFT: tr/test_stft
DIR_NAME_TRAIN_LOGMEL: tr/train_logmel
DIR_NAME_TRAIN_STFT: tr/train_stft
EPOCHS: 100
FRAMES: 5
GRAPH_TYPE: Log Mel
LIBROSA_HOP_LENGTH: 512
LIBROSA_N_FFT: 1024
LIBROSA_N_MELS: 64
LIBROSA_POWER: 1.0
LIBROSA_WIN_LENGTH: 1024
LOSS: mean_squared_error
OPTIMIZER: adam
PATIENCE: 13
PYAUDIO_CHANNELS: 1
PYAUDIO_CHUNK: 2048
PYAUDIO_FORMAT: pyaudio.paInt16
PYAUDIO_SECONDS: 3
SHUFFLE: true
THRESHOLD_LOGMEL: 33.9
TRAIN_TOTAL: 60
VALIDATION_SPLIT: 0.1
VERBOSE: 1
