AUDIO_SAMPLERATE: 16000
BATCH_SIZE: 128
DIR_NAME_MODEL: model/model_stft.hdf5
DIR_NAME_RESULT: result
DIR_NAME_TEST_STFT: tr/test_stft_parquet
DIR_NAME_TRAIN_STFT: tr/train_stft_parquet
DENOISE_MODEL: model/DTLN_norm_500h_saved_model
EPOCHS: 100
FRAMES: 1
LIBROSA_N_FFT: 512
LOSS: mean_squared_error
OPTIMIZER: adam
PATIENCE: 22
PYAUDIO_CHUNK: 1024
SHUFFLE: true
THRESHOLD_STFT: 33.9
TRAIN_TOTAL: 1320
VALIDATION_SPLIT: 0.1
VERBOSE: 1
